### ISSUE TITLE
使用termux测试时v2ray无法进行测速

### ISSUE THREAD

**Issue by aqiu817** [NyanChanMeow/SSRSpeed#109]
使用的是linux-arm64，安卓9。
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/SSRSpeed/ssrspeed/speed_test/speed_test.py", line 175, in __start_test
    client.startClient(config)
  File "/data/data/com.termux/files/home/SSRSpeed/ssrspeed/client_launcher/client_v2ray.py", line 35, in startClient
    self._process = subprocess.Popen(["./clients/v2ray-core/v2ray","--config","%s/config.json" % os.getcwd()],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 1700, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './clients/v2ray-core/v2ray'

**Comment by cangyin** [comment]
看起来这是个权限问题

**Comment by NyanChanMeow** [comment]
v2ray-core 的权限问题，自查一下
