### ISSUE TITLE
windows使用speedtestnet测速时出现如下错误

### ISSUE THREAD

**Issue by bren0524** [NyanChanMeow/SSRSpeed#16]
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\speedTest.py", line 50, in startTest
    s = speedtestnet.Speedtest()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\speedtestnet.py", line 1030, in __init__
    self.get_config()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\speedtestnet.py", line 1065, in get_config
    raise ConfigRetrievalError(e)
speedtestnet.ConfigRetrievalError: <urlopen error _ssl.c:1039: The handshake operation timed out>
[2019-03-24 21:19:13,628][ERROR][2336][main.py:388]
Traceback (most recent call last):
  File "main.py", line 368, in <module>
    _item["dspeed"] = testRes[0]
TypeError: 'int' object is not subscriptable
[2019-03-24 21:19:13,628][INFO][2336][shadowsocksR.py:113]ShadowsocksR terminated.
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\socks.py", line 832, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\socks.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\socks.py", line 844, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1087: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023F5645C7F0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:1087: [WinError 10061] 由于目标计算机积极拒绝，无法连 接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1087): Max retries exceeded with url: /api?auth=7gHcg0umEd7-Yyr5tiYc&app=SpeedTest&token=SpeedTest&action=nextConfig (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F5645C7F0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:1087: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 390, in <module>
    if (not ssr.nextWinConf()):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\shadowsocksR.py", line 72, in nextWinConf
    rep = requests.post("http://%s:%d/api?auth=%s" % (LOCAL_ADDRESS,LOCAL_PORT,self.__ssrAuth),params = param)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=1087): Max retries exceeded with url: /api?auth=7gHcg0umEd7-Yyr5tiYc&app=SpeedTest&token=SpeedTest&action=nextConfig (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F5645C7F0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:1087: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by bren0524** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\speedTest.py", line 50, in startTest
    s = speedtestnet.Speedtest()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\speedtestnet.py", line 1030, in __init__
    self.get_config()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\speedtestnet.py", line 1065, in get_config
    raise ConfigRetrievalError(e)
speedtestnet.ConfigRetrievalError: <urlopen error _ssl.c:1039: The handshake operation timed out>
[2019-03-24 21:19:13,628][ERROR][2336][main.py:388]
Traceback (most recent call last):
  File "main.py", line 368, in <module>
    _item["dspeed"] = testRes[0]
TypeError: 'int' object is not subscriptable
[2019-03-24 21:19:13,628][INFO][2336][shadowsocksR.py:113]ShadowsocksR terminated.
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\socks.py", line 832, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\socks.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\socks.py", line 844, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1087: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023F5645C7F0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:1087: [WinError 10061] 由于目标计算机积极拒绝，无法连 接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1087): Max retries exceeded with url: /api?auth=7gHcg0umEd7-Yyr5tiYc&app=SpeedTest&token=SpeedTest&action=nextConfig (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F5645C7F0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:1087: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 390, in <module>
    if (not ssr.nextWinConf()):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\shadowsocksR.py", line 72, in nextWinConf
    rep = requests.post("http://%s:%d/api?auth=%s" % (LOCAL_ADDRESS,LOCAL_PORT,self.__ssrAuth),params = param)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=1087): Max retries exceeded with url: /api?auth=7gHcg0umEd7-Yyr5tiYc&app=SpeedTest&token=SpeedTest&action=nextConfig (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F5645C7F0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:1087: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by NyanChanMeow** [comment]
speedtestnet 已停止支持，请使用socket方式

**Comment by bren0524** [comment]
> speedtestnet 已停止支持，请使用socket方式

[2019-03-24 21:24:48,723][INFO][8756][main.py:383]陆玖 - 中国 B (中转|回国) 浙江绍兴 0.5倍 - 电信联通 | 100Mbps - Loss:0.0% - TCP_Ping:18 - AvgSpeed:3.39MB/s - MaxSpeed:1.72MB/s
[2019-03-24 21:24:49,833][INFO][8756][main.py:360]Starting test for 陆玖 - 俄罗斯 A (联通|电信) 伯力 0.5倍 - OLVPS | 1Gbps
[2019-03-24 21:24:50,834][INFO][8756][speedTest.py:88]Testing latency to server.
[2019-03-24 21:24:52,656][INFO][8756][speedTest.py:44]Starting speed test with SOCKET
使用socket测速时，有几率测到某一节点后卡住，并且一直停留在当前节点。（这种情况在我之前使用fast测速时也有出现过）

**Comment by ranwen** [comment]
这bug修复已经提(gu)上(gu)日(gu)程了

**Comment by NyanChanMeow** [comment]
这个问题如果再git pull后还存在，请带--debug参数后上传日志

**Comment by bren0524** [comment]
> 这个问题如果再git pull后还存在，请带--debug参数后上传日志

[2019-03-24 21:55:45,860][INFO][11388][speedTest.py:88]Testing latency to server.
[2019-03-24 21:55:47,626][INFO][11388][speedTest.py:44]Starting speed test with SOCKET
[2019-03-24 22:10:34,447][ERROR][11388][stSocket.py:51]Parse location failed.
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

During handling of the above exception, another exception occurred:
git pull之后还是出现

**Comment by bren0524** [comment]
> 这bug修复已经提(gu)上(gu)日(gu)程了

加油 不要gugugu

**Comment by NyanChanMeow** [comment]
已实验性修复，暂时无法定位bug位置，麻烦请git pull Dev分支的最新版本并尝试复现。

**Comment by NyanChanMeow** [comment]
> > 这个问题如果再git pull后还存在，请带--debug参数后上传日志
> 
> [2019-03-24 21:55:45,860][INFO][11388][speedTest.py:88]Testing latency to server.
> [2019-03-24 21:55:47,626][INFO][11388][speedTest.py:44]Starting speed test with SOCKET
> [2019-03-24 22:10:34,447][ERROR][11388][stSocket.py:51]Parse location failed.
> Traceback (most recent call last):
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
> chunked=chunked)
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
> self._validate_conn(conn)
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn conn.connect() File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 344, in connect ssl_context=context) File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
> return context.wrap_socket(sock, server_hostname=server_hostname)
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
> session=session
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 853, in _create
> self.do_handshake()
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1117, in do_handshake
> self._sslobj.do_handshake()
> ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
> timeout=timeout
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
> _stacktrace=sys.exc_info()[2])
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 367, in increment
> raise six.reraise(type(error), error, _stacktrace)
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
> raise value.with_traceback(tb)
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
> chunked=chunked)
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
> self._validate_conn(conn)
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn conn.connect() File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 344, in connect ssl_context=context) File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
> return context.wrap_socket(sock, server_hostname=server_hostname)
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
> session=session
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 853, in _create
> self.do_handshake()
> File "C:\Users\Administrator.DESKTOP-KV2R00L\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1117, in do_handshake
> self._sslobj.do_handshake()
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))
> 
> During handling of the above exception, another exception occurred:
> git pull之后还是出现

这个属于正常现象，因为无法访问ip.sb导致的错误

**Comment by bren0524** [comment]
更新以后问题已解决
