### ISSUE TITLE
Window10 下使用出错

### ISSUE THREAD

**Issue by Askwind** [NyanChanMeow/SSRSpeed#26]
已经安装以下更新 和 库，还是出错，是有啥缺失了吗？
我是直接copy gui-config.json过来测试的。 
'python -m pip install --upgrade pip
pip3 install pillow
pip3 install requests
pip3 install pysocks'

`E:\Tools\SSRSpeed-2.4.4>python main.py -yu gui-config.json  -S speed
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    from SSRSpeed.Utils.ConfigParser.ShadowsocksParser import ShadowsocksParser as SSParser
  File "E:\Tools\SSRSpeed-2.4.4\SSRSpeed\Utils\ConfigParser\ShadowsocksParser.py", line 12, in <module>
    from SSRSpeed.Utils.ConfigParser.ShadowsocksParsers.ClashSSParser import ParserShadowsocksClash
  File "E:\Tools\SSRSpeed-2.4.4\SSRSpeed\Utils\ConfigParser\ShadowsocksParsers\ClashSSParser.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'`

**Comment by NyanChanMeow** [comment]
@Askwind 请安装pyyaml

**Comment by Askwind** [comment]
搞定！

**Comment by leader23** [comment]
请问执行过后没有然后了是因为什么呢？

[2019-07-18 03:03:23,714][INFO][12436][BaseParser.py:141]XXXX
[2019-07-18 03:03:23,715][INFO][12436][BaseParser.py:141]XXXX
[2019-07-18 03:03:23,715][INFO][12436][BaseParser.py:141]XXXX
[2019-07-18 03:03:23,715][INFO][12436][BaseParser.py:141]XXXX
[2019-07-18 03:03:23,716][INFO][12436][BaseParser.py:141]XXXX
[2019-07-18 03:03:23,717][INFO][12436][BaseParser.py:141]XXXX
[2019-07-18 03:03:23,718][INFO][12436][SSRSpeedCore.py:167]109 node(s) will be test.
Before the test please confirm the nodes,Ctrl-C to exit. (Y/N)y

G:\Program Files\SSRSpeed-master>

**Comment by Hitiko** [comment]
@leader23 请  输  入  大  写  Y

**Comment by leader23** [comment]
> @ leader23请输入大写 Y.

解决了，非常感谢 @Hitiko
