### ISSUE TITLE
请问这报错是啥问题？

### ISSUE THREAD

**Issue by dubstep1212** [NyanChanMeow/SSRSpeed#31]
用win10随便测了2个节点，速度都为0，而且报错了，请问是啥原因？

Before the test please confirm the nodes,Ctrl-C to exit. (Y/N)Y
[2019-05-24 16:50:11,591][INFO][1276][SpeedTestCore.py:131]Test mode : speed and tcp ping.Test method : SOCKET.
[2019-05-24 16:50:13,594][INFO][1276][checkPlatform.py:9]Platform Info : Windows-10-10.0.17763-SP0
[2019-05-24 16:50:13,609][INFO][1276][ShadowsocksR.py:60]Starting ShadowsocksR-libev with server hkthome1.puffvip.com:80
[2019-05-24 16:50:13,622][INFO][1276][SpeedTestCore.py:146]Starting test for 香港 - HKT [1/2]
[2019-05-24 16:50:13,626][INFO][1276][IPGeo.py:43]Translating hkthome1.puffvip.com to ipv4.
[2019-05-24 16:50:13,629][INFO][1276][IPGeo.py:60]Starting Geo IP.
[2019-05-24 16:50:19,667][ERROR][1276][IPGeo.py:70]Geo IP Failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1034: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\OverTheWall\SSRSpeed-2.4.6\SSRSpeed\Utils\IPGeo.py", line 66, in IPLoc
    },timeout=5)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Read timed out. (read timeout=5)
[2019-05-24 16:50:19,691][INFO][1276][SpeedTestCore.py:68]Node inbound IP : *, Geo : N/A Unknown City, N/A
[2019-05-24 16:50:20,711][INFO][1276][SpeedTestMethods.py:85]Testing latency to server.
[2019-05-24 16:50:21,892][INFO][1276][SpeedTestMethods.py:41]Starting speed test with SOCKET
[2019-05-24 16:50:21,892][INFO][1276][IPGeo.py:18]Starting parse location.
[2019-05-24 16:50:23,463][INFO][1276][IPGeo.py:24]Server Country Code : HK,Continent Code : AS,ISP : HKT Limited
[2019-05-24 16:50:23,463][INFO][1276][stSocket.py:140]No rule matched.using default.
[====================] [100%/100%] [0.00 MB/s]
[2019-05-24 16:50:33,886][INFO][1276][stSocket.py:226]Fetched 5.71 KB in 10.38 s.
[2019-05-24 16:50:33,887][INFO][1276][SpeedTestMethods.py:81]Testing latency to google.
[2019-05-24 16:50:38,719][INFO][1276][IPGeo.py:60]Starting Geo IP.
[2019-05-24 16:50:43,767][ERROR][1276][IPGeo.py:70]Geo IP Failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1034: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\OverTheWall\SSRSpeed-2.4.6\SSRSpeed\Utils\IPGeo.py", line 66, in IPLoc
    },timeout=5)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Read timed out. (read timeout=5)
[2019-05-24 16:50:43,850][INFO][1276][SpeedTestCore.py:84]Node outbound IP : N/A, Geo : N/A Unknown City, N/A
[2019-05-24 16:50:44,854][INFO][1276][checkPlatform.py:9]Platform Info : Windows-10-10.0.17763-SP0
[2019-05-24 16:50:44,856][INFO][1276][ClientBase.py:45]Client terminated.
[2019-05-24 16:50:45,857][INFO][1276][SpeedTestCore.py:194]香港 - HKT - Loss:0.0%% - TCP_Ping:35 - AvgSpeed:0.00MB/s - MaxSpeed:0.00MB/s
[2019-05-24 16:50:45,864][INFO][1276][checkPlatform.py:9]Platform Info : Windows-10-10.0.17763-SP0
[2019-05-24 16:50:45,885][INFO][1276][ShadowsocksR.py:60]Starting ShadowsocksR-libev with server hkthome1.puffvip.com:543
[2019-05-24 16:50:45,914][INFO][1276][SpeedTestCore.py:146]Starting test for 香港 - HKT [2/2]
[2019-05-24 16:50:45,953][INFO][1276][IPGeo.py:43]Translating hkthome1.puffvip.com to ipv4.
[2019-05-24 16:50:45,955][INFO][1276][IPGeo.py:60]Starting Geo IP.
[2019-05-24 16:50:47,178][INFO][1276][SpeedTestCore.py:68]Node inbound IP : *, Geo : Hong Kong Lam Tin, HKT Limited
[2019-05-24 16:50:48,182][INFO][1276][SpeedTestMethods.py:85]Testing latency to server.
[2019-05-24 16:50:49,364][INFO][1276][SpeedTestMethods.py:41]Starting speed test with SOCKET
[2019-05-24 16:50:49,366][INFO][1276][IPGeo.py:18]Starting parse location.
[2019-05-24 16:50:49,582][INFO][1276][IPGeo.py:24]Server Country Code : HK,Continent Code : AS,ISP : HKT Limited
[2019-05-24 16:50:49,583][INFO][1276][stSocket.py:140]No rule matched.using default.
[====================] [100%/100%] [0.00 MB/s]
[2019-05-24 16:50:59,697][INFO][1276][stSocket.py:226]Fetched 5.71 KB in 10.11 s.
[2019-05-24 16:50:59,699][INFO][1276][SpeedTestMethods.py:81]Testing latency to google.
[2019-05-24 16:51:00,529][INFO][1276][IPGeo.py:60]Starting Geo IP.
[2019-05-24 16:51:00,716][INFO][1276][SpeedTestCore.py:84]Node outbound IP : *, Geo : Hong Kong Lam Tin, HKT Limited
[2019-05-24 16:51:01,719][INFO][1276][checkPlatform.py:9]Platform Info : Windows-10-10.0.17763-SP0
[2019-05-24 16:51:01,720][INFO][1276][ClientBase.py:45]Client terminated.
[2019-05-24 16:51:02,722][INFO][1276][SpeedTestCore.py:194]香港 - HKT - Loss:0.0%% - TCP_Ping:36 - AvgSpeed:0.00MB/s - MaxSpeed:0.00MB/s
[2019-05-24 16:51:02,735][INFO][1276][exportResult.py:41]Set colors as origin.
[2019-05-24 16:51:02,755][INFO][1276][exportResult.py:273]Result exported as ./results/2019-05-24-16-51-02.json
[2019-05-24 16:51:02,893][INFO][1276][exportResult.py:213]Result image saved as ./results/2019-05-24-16-51-02.png

**Comment by Taowyoo** [comment]
你解决这个问题了么

**Comment by Masstone** [comment]
> 用win10随便测了2个节点，速度都为0，而且报错了，请问是啥原因？
> 
> Before the test please confirm the nodes,Ctrl-C to exit. (Y/N)Y
> [2019-05-24 16:50:11,591][INFO][1276][SpeedTestCore.py:131]Test mode : speed and tcp ping.Test method : SOCKET.
> [2019-05-24 16:50:13,594][INFO][1276][checkPlatform.py:9]Platform Info : Windows-10-10.0.17763-SP0
> [2019-05-24 16:50:13,609][INFO][1276][ShadowsocksR.py:60]Starting ShadowsocksR-libev with server hkthome1.puffvip.com:80
> [2019-05-24 16:50:13,622][INFO][1276][SpeedTestCore.py:146]Starting test for 香港 - HKT [1/2]
> [2019-05-24 16:50:13,626][INFO][1276][IPGeo.py:43]Translating hkthome1.puffvip.com to ipv4.
> [2019-05-24 16:50:13,629][INFO][1276][IPGeo.py:60]Starting Geo IP.
> [2019-05-24 16:50:19,667][ERROR][1276][IPGeo.py:70]Geo IP Failed.
> Traceback (most recent call last):
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
> self._validate_conn(conn)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn conn.connect() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 344, in connect ssl_context=context) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
> return context.wrap_socket(sock, server_hostname=server_hostname)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 412, in wrap_socket
> session=session
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 853, in _create
> self.do_handshake()
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1117, in do_handshake
> self._sslobj.do_handshake()
> socket.timeout: _ssl.c:1034: The handshake operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
> timeout=timeout
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
> _stacktrace=sys.exc_info()[2])
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 367, in increment
> raise six.reraise(type(error), error, _stacktrace)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
> raise value
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
> chunked=chunked)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
> self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 306, in _raise_timeout
> raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
> urllib3.exceptions.ReadTimeoutError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Read timed out. (read timeout=5)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "F:\OverTheWall\SSRSpeed-2.4.6\SSRSpeed\Utils\IPGeo.py", line 66, in IPLoc
> },timeout=5)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 75, in get
> return request('get', url, params=params, **kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
> return session.request(method=method, url=url, **kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
> resp = self.send(prep, **send_kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
> r = adapter.send(request, **kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 529, in send
> raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Read timed out. (read timeout=5)
> [2019-05-24 16:50:19,691][INFO][1276][SpeedTestCore.py:68]Node inbound IP : *, Geo : N/A Unknown City, N/A
> [2019-05-24 16:50:20,711][INFO][1276][SpeedTestMethods.py:85]Testing latency to server.
> [2019-05-24 16:50:21,892][INFO][1276][SpeedTestMethods.py:41]Starting speed test with SOCKET
> [2019-05-24 16:50:21,892][INFO][1276][IPGeo.py:18]Starting parse location.
> [2019-05-24 16:50:23,463][INFO][1276][IPGeo.py:24]Server Country Code : HK,Continent Code : AS,ISP : HKT Limited
> [2019-05-24 16:50:23,463][INFO][1276][stSocket.py:140]No rule matched.using default.
> [====================] [100%/100%] [0.00 MB/s]
> [2019-05-24 16:50:33,886][INFO][1276][stSocket.py:226]Fetched 5.71 KB in 10.38 s.
> [2019-05-24 16:50:33,887][INFO][1276][SpeedTestMethods.py:81]Testing latency to google.
> [2019-05-24 16:50:38,719][INFO][1276][IPGeo.py:60]Starting Geo IP.
> [2019-05-24 16:50:43,767][ERROR][1276][IPGeo.py:70]Geo IP Failed.
> Traceback (most recent call last):
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
> self._validate_conn(conn)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn conn.connect() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 344, in connect ssl_context=context) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
> return context.wrap_socket(sock, server_hostname=server_hostname)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 412, in wrap_socket
> session=session
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 853, in _create
> self.do_handshake()
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1117, in do_handshake
> self._sslobj.do_handshake()
> socket.timeout: _ssl.c:1034: The handshake operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
> timeout=timeout
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
> _stacktrace=sys.exc_info()[2])
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 367, in increment
> raise six.reraise(type(error), error, _stacktrace)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
> raise value
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
> chunked=chunked)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
> self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 306, in _raise_timeout
> raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
> urllib3.exceptions.ReadTimeoutError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Read timed out. (read timeout=5)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "F:\OverTheWall\SSRSpeed-2.4.6\SSRSpeed\Utils\IPGeo.py", line 66, in IPLoc
> },timeout=5)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 75, in get
> return request('get', url, params=params, **kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
> return session.request(method=method, url=url, **kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
> resp = self.send(prep, **send_kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
> r = adapter.send(request, **kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 529, in send
> raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Read timed out. (read timeout=5)
> [2019-05-24 16:50:43,850][INFO][1276][SpeedTestCore.py:84]Node outbound IP : N/A, Geo : N/A Unknown City, N/A
> [2019-05-24 16:50:44,854][INFO][1276][checkPlatform.py:9]Platform Info : Windows-10-10.0.17763-SP0
> [2019-05-24 16:50:44,856][INFO][1276][ClientBase.py:45]Client terminated.
> [2019-05-24 16:50:45,857][INFO][1276][SpeedTestCore.py:194]香港 - HKT - Loss:0.0%% - TCP_Ping:35 - AvgSpeed:0.00MB/s - MaxSpeed:0.00MB/s
> [2019-05-24 16:50:45,864][INFO][1276][checkPlatform.py:9]Platform Info : Windows-10-10.0.17763-SP0
> [2019-05-24 16:50:45,885][INFO][1276][ShadowsocksR.py:60]Starting ShadowsocksR-libev with server hkthome1.puffvip.com:543
> [2019-05-24 16:50:45,914][INFO][1276][SpeedTestCore.py:146]Starting test for 香港 - HKT [2/2]
> [2019-05-24 16:50:45,953][INFO][1276][IPGeo.py:43]Translating hkthome1.puffvip.com to ipv4.
> [2019-05-24 16:50:45,955][INFO][1276][IPGeo.py:60]Starting Geo IP.
> [2019-05-24 16:50:47,178][INFO][1276][SpeedTestCore.py:68]Node inbound IP : *, Geo : Hong Kong Lam Tin, HKT Limited
> [2019-05-24 16:50:48,182][INFO][1276][SpeedTestMethods.py:85]Testing latency to server.
> [2019-05-24 16:50:49,364][INFO][1276][SpeedTestMethods.py:41]Starting speed test with SOCKET
> [2019-05-24 16:50:49,366][INFO][1276][IPGeo.py:18]Starting parse location.
> [2019-05-24 16:50:49,582][INFO][1276][IPGeo.py:24]Server Country Code : HK,Continent Code : AS,ISP : HKT Limited
> [2019-05-24 16:50:49,583][INFO][1276][stSocket.py:140]No rule matched.using default.
> [====================] [100%/100%] [0.00 MB/s]
> [2019-05-24 16:50:59,697][INFO][1276][stSocket.py:226]Fetched 5.71 KB in 10.11 s.
> [2019-05-24 16:50:59,699][INFO][1276][SpeedTestMethods.py:81]Testing latency to google.
> [2019-05-24 16:51:00,529][INFO][1276][IPGeo.py:60]Starting Geo IP.
> [2019-05-24 16:51:00,716][INFO][1276][SpeedTestCore.py:84]Node outbound IP : *, Geo : Hong Kong Lam Tin, HKT Limited
> [2019-05-24 16:51:01,719][INFO][1276][checkPlatform.py:9]Platform Info : Windows-10-10.0.17763-SP0
> [2019-05-24 16:51:01,720][INFO][1276][ClientBase.py:45]Client terminated.
> [2019-05-24 16:51:02,722][INFO][1276][SpeedTestCore.py:194]香港 - HKT - Loss:0.0%% - TCP_Ping:36 - AvgSpeed:0.00MB/s - MaxSpeed:0.00MB/s
> [2019-05-24 16:51:02,735][INFO][1276][exportResult.py:41]Set colors as origin.
> [2019-05-24 16:51:02,755][INFO][1276][exportResult.py:273]Result exported as ./results/2019-05-24-16-51-02.json
> [2019-05-24 16:51:02,893][INFO][1276][exportResult.py:213]Result image saved as ./results/2019-05-24-16-51-02.png

我也遇到了，有的节点OK，有的节点就会出这个问题，解决了么，怎么被close了
