### ISSUE TITLE
Shadowsocks-libev需要提前设置什么吗

### ISSUE THREAD

**Issue by zhiquan304** [NyanChanMeow/SSRSpeed#51]
ubuntu 19
使用 apt 安装的Shadowsocks-libev， 报如下错误：
```
[2019-07-25 01:51:11,868][INFO][140175035041600][IPGeo.py:45]Translating video2.host.ssr-lb.com to ipv4.
[2019-07-25 01:51:11,894][INFO][140175035041600][IPGeo.py:62]Starting Geo IP.
[2019-07-25 01:51:11,897][ERROR][140175035041600][IPGeo.py:75]Geo IP Failed.
Traceback (most recent call last):
  File "/home/zhiquan/.local/lib/python3.7/site-packages/socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/socks.py", line 88, in _new_conn
    **extra_kw
  File "/home/zhiquan/.local/lib/python3.7/site-packages/socks.py", line 209, in create_connection
    raise err
  File "/home/zhiquan/.local/lib/python3.7/site-packages/socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "/home/zhiquan/.local/lib/python3.7/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1087: [Errno 111] Connection refused
```
提示无法连接到 ss 。
同时有个现象时 webui 一直报` Connect to backend failed.Retry in 10s.`

**Comment by NyanChanMeow** [comment]
@traim304 请编译安装shadowsocks-libev

**Comment by traim304** [comment]
使用编译安装后， 问题依旧。
尝试修改` sudo vi /etc/shadowsocks-libev/config.json` 中的默认监听端口“8388” 为 “1087”。
报错变成了 `socket.timeout: timed out`

**Comment by traim304** [comment]
@NyanChanMeow 使用编译安装后， 问题依旧。
尝试修改 sudo vi /etc/shadowsocks-libev/config.json 中的默认监听端口“8388” 为 “1087”。
报错变成了 socket.timeout: timed out

**Comment by NyanChanMeow** [comment]
请检查是否有程序占用1087端口，并使用--debug参数获取详细输出（命令行界面检查一下SS-libev的运行状况

**Comment by traim304** [comment]
@NyanChanMeow 1087没有占用。从 log 上看就是 GEOIP 拿不到，还有一点是，一部分能拿到，一部分拿不到。再贴一下 debug 输出
```
[2019-07-31 09:40:42,293][INFO][140701094049600][IPGeo.py:62]Starting Geo IP.
[2019-07-31 09:40:42,295][ERROR][140701094049600][IPGeo.py:75]Geo IP Failed.
Traceback (most recent call last):
  File "/home/zhiquan/.local/lib/python3.7/site-packages/socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/socks.py", line 88, in _new_conn
    **extra_kw
  File "/home/zhiquan/.local/lib/python3.7/site-packages/socks.py", line 209, in create_connection
    raise err
  File "/home/zhiquan/.local/lib/python3.7/site-packages/socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "/home/zhiquan/.local/lib/python3.7/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1087: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/contrib/socks.py", line 110, in _new_conn
    "Failed to establish a new connection: %s" % error
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ff783f9a240>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/120.78.139.98 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ff783f9a240>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhiquan/PycharmProjects/SSRSpeed/SSRSpeed/Utils/IPGeo.py", line 68, in IPLoc
    },timeout=5)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/120.78.139.98 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ff783f9a240>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2019-07-31 09:40:42,296][INFO][140701094049600][SpeedTestCore.py:71]Node inbound IP : 120.78.139.98, Geo : N/A Unknown City, N/A
IPv6 support
2019-07-31 09:40:42 WARNING  shell.py:116 warning: your timeout 10 seems too short
2019-07-31 09:40:42 INFO     util.py:85 loading libsodium from libsodium.so.23
```

话说可不可能是因为访问 geoip 时。 ssr 还没有启动

**Comment by ioxuy** [comment]
在 \SSRSpeed\ssrspeed\speed_test\speed_test.py 166行后面添加time.sleep(0.1)解决,应该有更好的办法?
我测试环境是ubuntu1404

**Comment by NyanChanMeow** [comment]
@ioxuy 近期会加上关于客户端启动检测的部分，应该就是客户端未启动导致的问题

**Comment by ioxuy** [comment]
> @ioxuy 近期会加上关于客户端启动检测的部分，应该就是客户端未启动导致的问题

应该是这样的,我在windows下面测试没有这个问题,可能就是因为Python版的ssr启动慢一些

**Comment by NyanChanMeow** [comment]
@ioxuy [e9fc06e](https://github.com/NyanChanMeow/SSRSpeed/commit/e9fc06e529a2a6d5aab31175b3c04a720336a613) 已尝试修复该问题，可以试一下

**Comment by ioxuy** [comment]
> @ioxuy [e9fc06e](https://github.com/NyanChanMeow/SSRSpeed/commit/e9fc06e529a2a6d5aab31175b3c04a720336a613) 已尝试修复该问题，可以试一下

我测试了下,暂时没发现问题,谢谢
