### ISSUE TITLE
Errno61

### ISSUE THREAD

**Issue by Upapanow** [NyanChanMeow/SSRSpeed#54]
Traceback (most recent call last):
  File "/Users/xxx/SSRSpeed/SSRSpeed/Utils/IPGeo.py", line 68, in IPLoc
    },timeout=5)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip/xxx.xxx.xxx.xxx (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1069dcc18>: Failed to establish a new connection: [Errno 61] Connection refused'))
每个节点都会报

**Comment by NyanChanMeow** [comment]
- 若为SSR
   - 请检查shadowoscksr-libev是否被WindowsDefender或者其他安全软件查杀，目前暂无方案解决交叉编译出的shadowoskcsr-libev被安全软件查杀的问题
   - 尝试使用shadowosocksr-c#客户端，具体方法见文档
 - 若为V2Ray
   - 请确认V2Ray-Core存在于 `./clients/v2ray-core` 文件夹中，需要`v2ctl.exe`和`v2ray.exe` (以Windows平台为例)
 - 若为其他代理类型或者确认无上述情况则需要协商一个方式发送完整日志文件
