### ISSUE TITLE
ubuntu python3 error UnicodeEncodeError

### ISSUE THREAD

**Issue by qoli** [NyanChanMeow/SSRSpeed#58]
已经按照 Readme 安装好所有的依赖
```
root@ubuntu:~/SSRSpeed# python3 main.py 
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    options,args = cli_cfg.init(VERSION)
  File "/root/SSRSpeed/ssrspeed/shell/cli.py", line 195, in init
    parser.print_help()
  File "/usr/lib/python3.6/optparse.py", line 1647, in print_help
    file.write(self.format_help())
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1716-1717: ordinal not in range(256)
```

**Comment by NyanChanMeow** [comment]
请尝试将终端编码设置为 UTF-8
