### ISSUE TITLE
什么情况都不可用

### ISSUE THREAD

**Issue by shzxm** [NyanChanMeow/SSRSpeed#9]
![image](https://user-images.githubusercontent.com/9905297/54073482-9ad13000-42c2-11e9-9b57-fe1492e15b21.png)
重复显示同一个错误
requirements.txt里边的东西安装正常.没有报错
更改端口也试过了
没有显示端口占用.
打开或不打开ssr也不行.
测速结果有ping没速度
使用测速代码为
python main.py -u https://mocloudplus.com/link/ABCDEFG123456?mu=0 --include 香港 -e png -m speedtestnet -y

**Comment by ranwen** [comment]
1 确定将链接修改为自己的订阅链接?
2 确定是否能使用ssr-py(检查目录是否有config.json) 若有 执行
`python3 ./shadowsocksr/shadowsocks/local.py -c config.json`
若能成功运行ssr-py 但程序依旧报错 请发送完整日志

**Comment by shzxm** [comment]
确定修改为自己的.防泄漏.用的示例订阅地址
根目录下有config.json 
但是./shadowsocksr/shadowsocks/里边没有.

**Comment by shzxm** [comment]
![image](https://user-images.githubusercontent.com/9905297/54075409-f4912480-42d9-11e9-8587-4aae383a481d.png)
执行命令后显示这个

**Comment by ranwen** [comment]
。。。
1 cd到speedtest主程序目录而不是ssr目录
2 你应该运行python3而不是pip3

**Comment by ranwen** [comment]
哦 应该使用python命令而不是python3

**Comment by shzxm** [comment]
emmmm......wait

**Comment by shzxm** [comment]
![image](https://user-images.githubusercontent.com/9905297/54075494-fb6c6700-42da-11e9-8182-721a5aee6508.png)

2019-03-10 02:19:00 WARNING  shell.py:116 warning: your timeout 10 seems too short
Traceback (most recent call last):
  File "./shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "./shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\shzxm\SSRSpeed\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\shzxm\SSRSpeed\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\shzxm\SSRSpeed\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\shzxm\SSRSpeed\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\shzxm\SSRSpeed\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\shzxm\SSRSpeed\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\shzxm\SSRSpeed\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 40, in load_libsodium
    'libsodium')
  File "C:\Users\shzxm\SSRSpeed\shadowsocksr\shadowsocks\..\shadowsocks\crypto\util.py", line 83, in find_library
    lib = CDLL(path)
  File "C:\Users\shzxm\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by ranwen** [comment]
使用chacha20系列加密的出现类似问题。可自行从 https://github.com/jedisct1/libsodium/releases/download/1.0.17/libsodium-1.0.17-msvc.zip 下载dll进行替换测试
