### ISSUE TITLE
No module named "request"

### ISSUE THREAD

**Issue by zhoukeming01** [NyanChanMeow/SSRSpeed#90]
`$ python main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from ssrspeed.core import SSRSpeedCore
  File "/storage/emulated/0/文档•学习/Github/SSRSpeed/ssrspeed/core/__init__.py", line 3, in <module>
    from .ssrspeed_core import SSRSpeedCore
  File "/storage/emulated/0/文档•学习/Github/SSRSpeed/ssrspeed/core/ssrspeed_core.py", line 13, in <module>
    from ..client_launcher import ShadowsocksClient as SSClient
  File "/storage/emulated/0/文档•学习/Github/SSRSpeed/ssrspeed/client_launcher/__init__.py", line 4, in <module>
    from .client_shadowsocksr import ShadowsocksR as ShadowsocksRClient
  File "/storage/emulated/0/文档•学习/Github/SSRSpeed/ssrspeed/client_launcher/client_shadowsocksr.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
$`
使用Android的Termux最新版

**Comment by zhoukeming01** [comment]
Solved
