### ISSUE TITLE
最近很长一段时间老这样Geo IP Failed

### ISSUE THREAD

**Issue by FrancoWay** [NyanChanMeow/SSRSpeed#99]
[2020-03-13 20:44:57,186][INFO][3328][speed_test.py:162]Starting test 忍者云 - Advanced|沪>新01|3.0|NF* - 7500 单端口 [2/34]
[2020-03-13 20:44:57,186][INFO][3328][platform_check.py:9]Platform Info : Windows-10-10.0.17763-SP0
[2020-03-13 20:44:57,188][INFO][3328][platform_check.py:9]Platform Info : Windows-10-10.0.17763-SP0
[2020-03-13 20:44:57,195][INFO][3328][client_shadowsocksr.py:60]Starting ShadowsocksR-libev with server shanghaientry.host-sub.com:7500
[2020-03-13 20:44:58,197][INFO][3328][speed_test.py:191]Client started.
127.0.0.1 - - [13/Mar/2020 20:44:58] "GET /getresults HTTP/1.1" 200 -
[2020-03-13 20:44:59,209][INFO][3328][geo_ip.py:45]Translating shanghaientry.host-sub.com to ipv4.
[2020-03-13 20:44:59,209][INFO][3328][geo_ip.py:62]Starting Geo IP.
127.0.0.1 - - [13/Mar/2020 20:45:01] "GET /getresults HTTP/1.1" 200 -
[2020-03-13 20:45:02,628][ERROR][3328][geo_ip.py:75]Geo IP Failed.
Traceback (most recent call last):
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SSRSpeed\ssrspeed\utils\geo_ip.py", line 68, in IPLoc
    },timeout=5)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\FrancoWay\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))
[2020-03-13 20:45:02,634][INFO][3328][speed_test.py:100]Node inbound IP : 139.226.18.124, Geo : N/A Unknown City, N/A

**Comment by cangyin** [comment]
这是服务器端的问题，并不是测试脚本的问题。看来你需要换服务器。

**Comment by FrancoWay** [comment]
> 这是服务器端的问题，并不是测试脚本的问题。看来你需要换服务器。

我也这么觉得，但是我看其他人能够正常使用ssrspeed测速啊
![image](https://user-images.githubusercontent.com/3960268/76624693-bd022b80-6570-11ea-8b26-fc5cb2793d99.png)

**Comment by cangyin** [comment]
测速结果与你所处地区及网络供应商有关。

 我这里也还能正常测速。
![2020-03-13-22-06-51](https://user-images.githubusercontent.com/50256182/76629781-ce036a80-6579-11ea-885b-ee41f01af12e.png)

**Comment by cangyin** [comment]
测速结果与你所处地区及网络供应商有关。

我这里也还能正常测速。
![image](https://user-images.githubusercontent.com/50256182/76630138-731e4300-657a-11ea-87e6-2f984a184578.png)
（ 图片内含网址信息，未征得同意，故使用了马赛克）

**Comment by cangyin** [comment]
你重置一下机场的订阅链接，更新节点之后再试试吧。
我这里测了一下忍者云的基础节点，都正常。

**Comment by FrancoWay** [comment]
> 你重置一下机场的订阅链接，更新节点之后再试试吧。也或许是套餐到期的原因。我这里测了一下忍者云的基础节点，都正常。

或者和我这边的网络环境有关系？很是奇怪，我用macbook在公司跑ssrspeed也是会这样
